FROM node:20-alpine

WORKDIR /app

# RUN apk add --no-cache bash
# RUN npm install -g @angular/cli

# EXPOSE 4200

# # CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]
# CMD sh -c "npm install && ng serve --host 0.0.0.0 --port 4200"

RUN npm install -g @angular/cli

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 4200
CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "4200"]