version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      - redis
      - mongodb

    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sms_app_development
      - RAILS_ENV=development
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
      - TWILIO_PHONE_NUMBER=${TWILIO_PHONE_NUMBER}
      - DEVISE_JWT_SECRET_KEY=${DEVISE_JWT_SECRET_KEY}
      - REDIS_URL=redis://redis:6379/1
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    # command: bash -c "rm -f tmp/pids/server.pid && /rails/bin/rails server -p 3000 -b '0.0.0.0'"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  sidekiq:
    build: 
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - .:/rails
      - bundle_cache:/usr/local/bundle
    depends_on:
      - redis
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/sms_app_development
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/1
    working_dir: /rails

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/frontend/node_modules
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true
    stdin_open: true

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=sms_app_development

volumes:
  mongodb_data:
  bundle_cache:
  frontend_node_modules:
  redis_data: